### ISSUE TITLE
*** -[NSURL initFileURLWithPath:]: nil string parameter

### ISSUE THREAD

**Issue by fabdrol** [jasonkneen/UTiL#42]
I'm using the UI module in order to use `backgroundSize`. I'm getting a strange error though. Here's my alloy code and the error.

`<View module="ui" class="avatar-wrapper" backgroundSize="cover" width="96" height="96" backgroundImage="images/no-user.png"></View>`
I tried a `/` before `images` as well..

```
[ERROR] [iphone, 8.4, 192.168.1.6] {
  "message": "*** -[NSURL initFileURLWithPath:]: nil string parameter",
  "line": 38,
  "column": 70,
  "stack": "_resizeBackgroundImage\n_setBackgroundImage\ncreateView\nController\ncreateController\n\nemit\ndispatch\nsetState\n\n\nonload"
}
```

**Comment by fabdrol** [comment]
Since Alloy doesn't seem to work, I tried the manual approach:
```
var avatar = require('ui').createView({
      backgroundImage: Alloy.Globals.Profile.get('avatar'),
      backgroundSize: "cover",
      borderRadius: 45,
      width: "106%",
      height: "106%",
      top: "-3%",
      left: "-3%"
    });

    $.avatar.removeAllChildren();
    $.avatar.add(avatar);
```
This also yields an error, although a different one. 
`[ERROR] [iphone, 8.4, 192.168.1.6] [UI] Could not write downloaded file to: file:///Users/Fabian/Library/Developer/CoreSimulator/Devices/9BA4D310-6A18-484B-A693-D9E098825FA9/data/Containers/Data/Application/43762E64-18BD-4AC4-9F0F-C8E60C4538EE/tmp/1f6ca17ecbc1b15cde12647104d1344091f3ecaa.com/696911963770382/picture`. 

When I try to use `/image/foo.png`, the other error appears.

**Comment by FokkeZB** [comment]
Does the sample app work for you? I just ran that and it works fine with similar paths:

https://github.com/FokkeZB/UTiL/blob/master/app/views/ui.xml

**Comment by botmaster** [comment]
Same issue.
Work great with remote url but fail with local image.
@fabdrol any workaround ?

**Comment by botmaster** [comment]
Ok I found a solution.
Try to change the line 177 : `originalFile = Ti.Filesystem.getFile(originalPath);`
To : `originalFile = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, originalPath);`

**Comment by FokkeZB** [comment]
Thanks @botmaster! Could you verify that works on both iOS and Android and send a PR?

**Comment by botmaster** [comment]
That works on both iOS and Android.
PR send.
