### ISSUE TITLE
Image URL without file extension fails

### ISSUE THREAD

**Issue by shekyboy** [jasonkneen/UTiL#43]
@FokkeZB 
Try this URL as a backgroundImage on a view with module="ui"
http://scene7.targetimg1.com/is/image/Target/14892950?wid=480&hei=480

Get the following error on the console and the image never renders
`[UI] Could not write downloaded file to: file:///Users/shekyboy/Library/Developer/CoreSimulator/Devices/2BA6217A-8675-4839-B11C-63140D25DC0E/data/Containers/Data/Application/CB611D38-3182-46A2-A480-1039923DC56C/tmp/dd511f123993e678b57373e7d51626b9dd7f3fe5.com/is/image/Target/14892950%3Fwid=480&hei=480`

Think this might be an issue with servers which serve images dynamically and expect clients to operate using mime type information rather than extensions in the URL.

Any recommendations on how to fix this

**Comment by shekyboy** [comment]
The issue is in deriving the local file extension from the URL. The local system doesnt quite care about this and the View control also doesnt care about it. In other words it could be any extension and the image would still render (iOS atleast)

So hack for the time being:

```
function _getTargetFile(originalPath, targetId, parent) {

	//var targetFilename = Ti.Utils.sha1(originalPath + '_' + targetId) + originalPath.substr(originalPath.lastIndexOf('.'));

// Instead of reusing the extension from the URL, simply use .x
	var targetFilename = Ti.Utils.sha1(originalPath + '_' + targetId) + ".x";
	var targetFile = Ti.Filesystem.getFile(parent || Ti.Filesystem.applicationCacheDirectory, targetFilename);

	return targetFile;
}
```

**Comment by FokkeZB** [comment]
So the issue is that it doesn't work without an extension and it doesn't matter what the extension is? Or is the problem that with the current logic and your example url the "extension" will be `.com/is/image/Target/14892950?wid=480&hei=480` which contains `/`?

Could you try if a random extension works on Android as well?
